Received: from EMSTXS.Ontyme.Tymnet by X62.Tymnet; Tue, 7 Apr 87 10:44:23 PDT
From: TYMHQ.SUP@EMSTXS.Ontyme.Tymnet 
Date: 07 APR 87 17:44:30 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I16876@Ontyme.Tymnet 
Subject: Hotel Rates - San Jose Area 

April 6, 1987
 
MCDONNELL DOUGLAS CORPORATE RATES IN THE TYMNET HEADQUARTERS,
SAN JOSE AREA
 
Tymnet Contact:         Judi Athow 408/432-5313
 
 
DOUBLETREE HOTEL        5101 Great America Parkway, Santa Clara
408/727-5323            (Great America Parkway off 101)
                        RATE: $89 single
                        REFER TO GOLD LEAF #70040 WHEN MAKING
                        RESERVATION TO RECEIVE THE $89 RATE.
 
EMBASSY SUITE           2885 Lakeside Dr., Santa Clara
408/496-6400            (Bowers off 101)
                        RATE:  $89 single
 
HYATT                   1740 N. First St., San Jose
408/298-0300            RATE:  $84 single
 
RADISSON                1471 North 4th St., San Jose
408/298-0100            RATE:  $75 single or double
 
Red Lion                2050 Gateway Place, San Jose
408/287-5466            RATE:  $85 single or double
 
RESIDENCE INN           1080 Stuart Dr., Sunnyvale
408/720-8893            (Lawrence off 101)
                        RATE:  $80 Studio (single)
                              $100 Double
 
WHEN MAKING RESERVATIONS, STATE THAT YOU ARE WITH MCDONNELL
DOUGLAS AND WOULD LIKE TO RECEIVE THE CORPORATE RATE LISTED
ABOVE.
Received: from EMSTXS.Ontyme.Tymnet by X62.Tymnet; Tue, 7 Apr 87 12:44:32 PDT
From: NETS.S/BOURDEAU@EMSTXS.Ontyme.Tymnet 
Date: 07 APR 87 20:10:37 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I17013@Ontyme.Tymnet 
Subject: :LOG 
TECHNICALINSTRUCTORPOSITIONOPEN: 

TO: THE WORLD  
     
FR: STEPHEN BOURDEAU
     
DT: APRIL 7, 1986   
     
RE: TECHNICAL INSTRUCTOR POSITION OPEN  
     
     
TRAINING & EDUCATION IN SAN JOSE  HAS AN OPENING FOR A TECHNICAL 
INSTRUCTOR, NETWORK SYSTEMS SUPPORT TRAINING SECTION.  THE PERSON
SELECTED FOR THE POSITION WILL:    
     
  1) INSTRUCT IN IBM DATA COMMUNICATIONS, IBM SNA, AND TYMNET'S  
     IMPLEMENTATION OF 3270, SDLC AND SNA.   
     
  2) WORK WITH BOTH TYMNET USER DOCUMENTATION, TECHNICAL SERVICES
     AND NETWORK TECHNOLOGY DEVELOPMENT TO ASSESS, REVISE AND IM-
     PROVE CURRENT TRAINING COURSES.    
     
THE SUCCESSFUL CANDIDATE SHOULD HAVE:   
     
  - TYMNET EXPERIENCE, PREFERABLY IN COMMUNICATIONS CONSULTING   
    IN BOTH THE PRIVATE AND/OR PUBLIC NETWORK ARENA.   
     
  - TECHNICAL COMPETENCE IN ISIS, NODE CODE, NODE AND SLOT CODE  
    GENERATION ON THE PDPD-10'S.  ALSO A WORKING KNOWLEDEGE OF   
    THE NETWORK MONITORING AND CONTROL TOOLS; PROBE, TMCS, XRAY  
    AND DDT.   
     
  - EXPERIENCE IN THE IMPLEMENTATION OF OF 3270, SDLC AND/OR SNA 
    INTERFACE CODE IN THE PPUBLIC AND/OR PRIVATE NETWORKS.  
     
  - A SOUND KNOWLEDGE OF THE 3270, BSC AND SDLC/QLLC PROTOCOLS.  
     
  - FORMAL OR INFORMAL TECHING EXPERIENCE.   
     
  - ABILITY TO CONVEY COMPLEX CONCEPTS IN AN EASY TO UNDERSTAND MANNER.    
     
IF YOU KNOW OF ANYONE WHO WOULD BE INTERESTED, WITHIN OR OUTSIDE OF   
NETWORK SYSTEMS COMPANY (TYMNET), PLEASE SEND THE NAME OF THE CANDIDATE.   
IF IT IS AN INTERNAL PERSON, PLEASE SEND THE NAME OF IMMEDIATE MANAGER
TO STEPHEN BOURDEAU.
     
  - ONTYME:  NETS.S/BOURDEAU  
  - PHONE: (408) 432-5042
     
THANK YOU,
     
STEPHEN BOURDEAU    
NETWORK SYSTEMS SUPPORT TRAINING,  
SECTION MANAGER
Received: from EMSTXS.Ontyme.Tymnet by X930.Tymnet; Fri, 1 May 87 14:44:25 PDT
From: IPC.I/LOPES@EMSTXS.Ontyme.Tymnet 
Date: 01 MAY 87 21:37:24 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: TXS.SUP@Ontyme.Tymnet 
Message-id: A54843@Ontyme.Tymnet 
Subject: Informix seminar 

           McDonnell Douglas
           Information Processing Company
 
 
DATE>      1 May 1987  13:35 PDT
 
TO>        Carl Baltrunas                    Kenneth Holcomb
           Edsel Budar                       Rai-ki Huang
           Fred Canning                      Stephen Poppe
           Wayne Crabbs                      A.S. Rajaraman
           Bill Euske                        Gary Walker
           Bill Fischer
 
COPIES>    Ed Roop
 
FROM>      Ingrid Lopes (IPC.I/LOPES)
 
SUBJECT>   Informix seminar
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 
     On Wednesday, May 6th, at 1 pm, members of our 1022 replace-
     ment committee will be attending a presentation on Informix,
     located at 4100 Bohannon Drive in Menlo Park.  The Informix
     staff will be hosting this session exclusively for us, which
     allows us an excellent opportunity to get information that
     will answer our particular concerns.  We invite you to join
     us at this session or to designate a representative.  If you
     cannot attend but would like to ask some questions, send
     them along to me and we will have them answered by the
     Informix staff.  We may be attending several more exclusive
     sessions offered by other DBMS companies in the next few
     months.  I will notify you of those dates.  Please contact
     me at the above Ontyme name or call me at 446-8844.
 
     Best regards.........Ingrid Lopes
Received: from EMSTXS.Ontyme.Tymnet by X930.Tymnet; Fri, 8 May 87 10:44:51 PDT
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 08 MAY 87 18:15:25 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A57351@Ontyme.Tymnet 
Subject: Cupertino Data Center Shutdown 

Date:        May 8, 1987
 
To:          The World
 
From:        Bill Fischer
 
Subject:     Cupertino Data Center Shutdown
 
*****************************************************************
 
Effective   May  18,  1987,  the  following  employees  will   be 
relocated at the Fremont Data Center, 4340 Solar Way, Fremont, CA 
94537.                                                            
 
 
                          Old Number              New Number
 
Bill Fischer             408-446-7762            415-498-2521   
                                                 415-498-2522
 
Ed Roop                  408-446-6656            415-498-2562
 
Debbie Burns             408-446-6629            415-498-2515
 
Linda Freitas            408-446-6630            415-498-2516
 
Vivian Hiatt-Bock        408-446-7150            415-498-2563
 
Bob Jacobs               408-446-7759            415-498-2558
 
Jan Krivanec             408-446-7081            415-498-2556
 
Ingrid Lopes             408-446-8844            415-498-2564
 
Chia-Lin (Julian) Min    408-446-8039            415-498-2560
 
Landa Morris             408-446-6870            415-498-2557
 
Khanh-Quoc Nguyen        408-446-7670            415-498-2559
 
Resources/Validations    408-446-6315 or 6629    415-498-2514
 
Software Distribution    (See individual numbers above)
 
Sue Pal                  408-446-7705            415-498-2500
 
 
 
 
 
 
 
 
 
 


The  following employees will be relocated at Fremont Data Center 
as of May 4, 1987.
 
 
Bill Richardson          408-446-7705            415-498-2500
 
David Debroveck          408-446-7610            415-498-2500
 
 
 
 
****************************************************************
*                                                              *
*    THE CUPERTINO DATA CENTER WILL BE OFFICIALLY CLOSED ON    *
*    MAY 31, 1987.                                             *
*                                                              *
****************************************************************
Received: from EMSTXS.Ontyme.Tymnet by X930.Tymnet; Mon, 11 May 87 16:44:14 PDT
From: TYMHQ.SUP@EMSTXS.Ontyme.Tymnet 
Date: 12 MAY 87 00:17:22 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I32837@Ontyme.Tymnet 
Subject: Bert Novak's New Assignment 
BertNovak'sNewAssignment: 

                                     MCDONNELL DOUGLAS
                                 INFORMATION SYSTEMS GROUP
                                          TYMNET

DATE>      11 MAY 87  15:19

TO>        Tymnet

COPIES>    

FROM>      Clint DeGabrielle


SUBJECT>   Bert Novak's New Assignment


-----------------------------------------------------------------------


Effective April 27, 1987 Bert Novak has been appointed President
of McDonnell Douglas Field Service Company.  We are pleased with 
Bert's appointment and look forward to closely working with him.  
At the present time, we are in the process of selecting a successor
for Bert here at Tymnet.  It is our intention to keep Bert's 
group intact and to replace Bert as soon as possible.  

Until such time as a replacement is named, Bert's organization 
will report to me.



Clint DeGabrielle
Vice-President Marketing and Field Operations
Tymnet McDonnell Douglas

/to
Received: from EMSTXS.Ontyme.Tymnet by X930.Tymnet; Fri, 15 May 87 8:41:10 PDT
From: TYMOPS.V/STAFFORD@EMSTXS.Ontyme.Tymnet 
Date: 15 MAY 87 08:27:31 
To: TXS.D/COFFEY@EMSTXS.Ontyme.Tymnet 
Message-id: M92587@Ontyme.Tymnet 
Subject: access to group 44 
Resrom: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Resent-date: Fri, 15 May 87 11:10:33 PDT 
Resent-to: (Monitor Group:), Carl, Osman, Joe <JMS> 
Resent-cc: Craig <FletcherC>, TXSSup 
Networkvalidation: Group 44 access needed.

Dennis

Your request per the following ontyme has been completed.

Vida

Received: from X930.Tymnet by EMSTXS.Ontyme.Tymnet; Wed, 13 May 87 16:36:41 PDT
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Wed, 13 May 87 16:05:12 PDT 
To: netops.v/stafford@ontyme, nets.p/hidy@ontyme 
Subject: Network validation: Group 44 access needed. 
Resent-from: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Resent-date: Wed, 13 May 87 16:34:45 PDT 
Resent-to: TYMOPS.V/STAFFORD@ONTYME 



                                  MEMORANDUM


                                                              TYMCOM-X SYSTEMS

DATE:  13-May-87    16:06:18

  TO:  Vida Stafford

  CC:  Paul Hidy

FROM:  Dennis Coffey  (Tymcom-X Systems)

SUBJ:  Network validation:  Group 44 access needed. 

------------------------------------------------------------------------------

Vida,

    The four of us who support the Tymcom-X monitor and utilities need access
to outdial network hosts, in order to support Tymcom-X systems which are not
on the public network.  The need is not frequent, but when the need arises the
need is urgent.

    I have spoken with Paul Hidy about our need.  He indicated that he would
be informing you of his approval of our request.

    The usernames needing vlaidation in Group 44 are:
        DENCOFF
        CARL
        JMS
        OSMAN

    If there are any questions or problems with this request, please call me
at X2588 (415/794-2588), or Ontyme TXS.D/COFFEY.


                                                Thanks,
                                                Dennis Coffey
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Thu, 28 May 87 10:17:18 PDT 
To: (Monitor Group:), Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC>, TXSSup 
Subject: New phone numbers for Bldg. C former occupants. 

The folks from Bldg.  C, including the Resource Planning & Management unit and
the Software Distribution & Installation unit, have moved to Solar Way, so
they have new phone numbers.

On top of this, the tie line between here and Solar Way has been taken out.
Because of this, you have to get out of the old Tymshare telephone network
into the public phone network, then dial the exchange and the whole 4-digit
extension number to reach anyone over there.  This is also true of the PDP-10
operators, and Lenny.


the numbers are:

Ed Roop				415/498-2562
Julian Minh			415/498-2560
Vivian Hyatt			415/498-2563

    RPM:
Resources			415/498-2514
Jan Krivanic			415/498-2556
Landa Morris			415/498-2557

    SDI:
Bob Jacobs			415/498-2558
Khanh Nguyn			415/498-2559
Ingrid (Dolovitchenyj) Lopes	415/498-2564

I'm sure there are others, but these are the only ones I can think of whom we
would need to know.


-D.-
Received: from F29.Tymnet by X930.Tymnet; Mon, 1 Jun 87 12:21:00 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 1 Jun 87 12:20:10 PDT
Return-path: <IPC.I/LOPES@EMSTXS.Ontyme.Tymnet> 
From: IPC.I/LOPES@EMSTXS.Ontyme.Tymnet 
Date: 01 JUN 87 19:47:59 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: TXS.SUP@Ontyme.Tymnet 
Message-id: A65816@Ontyme.Tymnet 
Subject: Adabas seminar 

           McDonnell Douglas
           Information Processing Company
 
 
DATE>      1 June 1987  11:44 PDT
 
TO>        Edsel Budar                       Bill Euske
           Fred Canning                      Bill Fischer
           Regina Chen                       Kenneth Holcomb
           Paul Corcoran                     Rai-ki Huang
           Chung Lam                         Stephen Poppe
           A.S. Rajaraman                    Gary Walker
 
FROM>      Ingrid Lopes (IPC.I/LOPES)
 
SUBJECT>   Adabas seminar
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 
     On Wednesday, June 10th, at 10 am, members of our 1022 replacement
     committee will be hosting a presentation on Adabas by Software AG.
     The presentation will be held in the main conference room of the Fre-
     mont data center at 4340 Solar Way.  We invite you to join us at this
     meeting or to designate a representative.  If enough people indicate
     an interest, we will relocate the meeting to the Orchard Parkway
     facility for the convenience of South Bay personnel.  Please contact
     me at the above Ontyme ID or call me at 415/498-2564.
 
     Best regards........Ingrid Lopes
Received: from F29.Tymnet by X930.Tymnet; Tue, 2 Jun 87 16:15:26 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 2 Jun 87 16:08:30 PDT
Return-path: <TYMOPS.L/WALKER@EMSTXS.Ontyme.Tymnet> 
From: TYMOPS.L/WALKER@EMSTXS.Ontyme.Tymnet 
Date: 02 JUN 87 23:40:44 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M96648@Ontyme.Tymnet 
Subject: PROMOTION 
Promotion: 



DATE:  June 2, 1987

TO:    All ISG Bay Area Employees

FROM:  Chuck Herman

SUBJ:  Promotion


I am pleased to announce the promotion of Judy Carlson to
Supervisor Telecommunications.

Judy will oversee the Telecommunications section of
No. Ca. M.S.O.

With over 10 years of Telco background, she will be a welcome
addition to Facilities Management.

Judy can be reached at Orchard Parkway, extension 5315 or
TYMOPS.J/CARLSON.
Received: from F29.Tymnet by X930.Tymnet; Mon, 8 Jun 87 8:55:15 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 8 Jun 87 8:48:47 PDT
Return-path: <IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet> 
From: IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet 
Date: 08 JUN 87 16:26:07 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A68354@Ontyme.Tymnet 
Subject: ISG CONVERSION SERVICE 

                        ISG CONVERSION SERVICE

   THE ISG CONVERSION SERVICE IS SET UP TO SERVE THE NEEDS OF THE ISG 
USER COMMUNITY.  ALONG WITH THE CURRENT CONVERSIONS THAT WE HAVE THE 
CAPABILITY TO DO THERE ARE OVER 490 OTHER CONVERSION PACKAGES 
AVAILABLE TO US.  IF YOU HAVE A NEED TO CONVERT WORD PROCESSING FILES 
WHETHER IT IS WITHIN YOUR OWN DEPARTMENT OR WITH A CUSTOMER,  CALL US 
AND LET US KNOW IF WE CAN HELP YOU IN ANYWAY! 


                        ISG CONVERSION SERVICE
                        (314) 233-8250
                        307-2E-E15
Received: from F29.Tymnet by X930.Tymnet; Tue, 9 Jun 87 10:17:25 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 9 Jun 87 10:13:11 PDT
Return-path: <NETS.TTE@EMSTXS.Ontyme.Tymnet> 
From: NETS.TTE@EMSTXS.Ontyme.Tymnet 
Date: 09 JUN 87 17:40:21 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I44494@Ontyme.Tymnet 
Subject: TTE 100 
TTE100BasicDataCommunication: 

                            M E M O R A N D U M

                          NETWORK SYSTEMS COMPANY
                         NETWORK SYSTEMS MARKETING


DATE>      09 JUN 87  09:34

TO>        All Employees

COPIES>    

FROM>      Tymnet Training and Education


SUBJECT>   TTE 100  Basic Data Communication


-----------------------------------------------------------------------


     We have added a TTE 100 to the schedule of classes.  If you
would like to learn Basic Data Communications including
  a.  Computer Basics
  b.  Data Communications Basics
  c.  Data Communications Networks
enroll today via ontyme  :EXEC *** TTE.ENROLL

    The course will be held at the TTE facility 2665 N. First
Street, June 17, 18, 19.  Class begins at 8:30 am.  The MDC
employee fee is $135.00
Received: from F29.Tymnet by X930.Tymnet; Wed, 10 Jun 87 16:01:54 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 10 Jun 87 15:53:57 PDT
Return-path: <IPC.I/LOPES@EMSTXS.Ontyme.Tymnet> 
From: IPC.I/LOPES@EMSTXS.Ontyme.Tymnet 
Date: 10 JUN 87 23:38:01 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A69761@Ontyme.Tymnet 
Subject: 1022 Replacement Project 

 
DATE>      10 June 1987   3:33 PDT
 
TO>        Edsel Budar                       Bill Euske
           Fred Canning                      Bob Fultz
           Regina Chen                       Kenneth Holcomb
           Paul Corcoran                     Rai-ki Huang
           Chung Lam                         Stephen Poppe
           A.S. Rajaraman                    Gary Walker
 
FROM>      Ingrid Lopes
 
SUBJECT>   1022 Replacement Project
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     This is to remind you that we will be meeting with represent-
     atives from Oracle to discuss the benchmark we would like to run
     on that product.  We will host the meeting on Friday, June 12th,
     at 10 am, not 9 am as previously announced.  We  will meet in the
     Resource Support conference room at Solar.  We welcome your
     attendance and contributions to this benchmark process.  If you
     can attend, please call me at 415/498-2564.
 
     Best regards.......Ingrid Lopes
Received: from F29.Tymnet by X930.Tymnet; Tue, 16 Jun 87 10:19:03 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 16 Jun 87 9:29:46 PDT
Return-path: <NETS.TTE@EMSTXS.Ontyme.Tymnet> 
From: NETS.TTE@EMSTXS.Ontyme.Tymnet 
Date: 16 JUN 87 16:49:30 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I47474@Ontyme.Tymnet 
Subject: TTE Schedule Update 
TTEScheduleUpdate: 

                            M E M O R A N D U M

                          NETWORK SYSTEMS COMPANY
                         NETWORK SYSTEMS MARKETING


DATE>      16 JUN 87  08:47

TO>        All Employees

COPIES>    

FROM>      Tymnet Training and Education


SUBJECT>   TTE Schedule Update


-----------------------------------------------------------------------


TTE has add the following classes to the schedule-

     TTE 100 Basic Data Communication            June 17-19
     TTE 502 TYMNET Concepts                     July 8-17
     TTE 430 Assembly Language Programming       July 20-24
     TTE 440 TYMNET Engine Programming           July 27-31
     TTE 442 ISIS Slot Programming and Debugg.   September 14-25
     TTE 210 IBM Data Comm and Intro to SNA      October 12-16
     TTE 230 TYMNET 3270/CMT                     October 19-23
     TTE 240 TYMNET SNA                          October 26-30

To enroll for any TTE course through OnTyme access               
  :EXEC *** TTE.ENROLL
Received: from F29.Tymnet by X930.Tymnet; Mon, 22 Jun 87 12:16:16 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 22 Jun 87 12:02:57 PDT
Return-path: <FIN.SUP@EMSTXS.Ontyme.Tymnet> 
From: FIN.SUP@EMSTXS.Ontyme.Tymnet 
Date: 22 JUN 87 19:47:52 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A73490@Ontyme.Tymnet 
Subject: Use Tax 
UseTaxAccruals: 

                             MCDONNELL DOUGLAS
                          NETWORK SYSTEMS COMPANY
                          INTEROFFICE MEMORANDUM
 
 
 
MEMO NO:  TAX-CUP-JEL-039
 
DATE:     22 June 1987
 
SUBJECT:  Use Tax Accruals
 
TO:       DISTRIBUTION
 
FROM:     Jerrye Lizana, Senior Tax Specialist
 
___________________________________________________________________________
 
 
 
Purchases  made  from Field Service Company,  such  as  PC,  Printers,  and 
Software, are subject to Use Tax at the appropriate local rate.
 
The Use Tax will be charged against your cost center(s).
 
If you have any questions, please contact me at ext. 6042.
Received: from F29.Tymnet by X930.Tymnet; Mon, 27 Jul 87 11:44:30 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 27 Jul 87 11:34:31 PDT
Return-path: <TYMOPS.N/NILES@EMSTXS.Ontyme.Tymnet> 
From: TYMOPS.N/NILES@EMSTXS.Ontyme.Tymnet 
Date: 27 JUL 87 19:08:33 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M08084@Ontyme.Tymnet 
Subject: Removal of Trash for MOve 

     TO:       All South Bay MDC Personnel

     FROM:     Dick Denesha

     DATE:     July 27, 1987

     SUBJECT:  Removal of Trash for MOve
     =================================================================

     TRASH, TRASH and more TRASH.  Here is how we are going to get rid
     of it!!.

     Carts marked with TRASH will be placed in each building at
     various locations.  They may be used by anyone, and Facilities
     Maintenance or the janitor will empty them as needed.  If you
     need immediate service, call 446-8048 for action.  PLEASE! do not
     put any WET trash into these carts.

     Now is a good time to get rid of outdated phone books and
     directories.  There will be a limited number of new San Jose
     books available for the Fremont movees, so everyone else please
     bring your 1987 books with you.

     The ELECTRICAL POWER STRIPS, EXTENSION CORDS, HEATERS AND FANS
     will not be needed or allowed (except in special circumstances)
     in the new buildings.  Please leave them on your desk for pickup
     by Facilities Maintenance.

     If you have any questions, please contact your local maintenance
     person:

     VALLEY GREEN        IGNACIO GUERRERO              446-6008

     BUBB RD.            BILL HUNT                     446-6040

     LIBERTY             YASUO KOTAKA                  415/794-2550

     OPW                 SLIM DAVENPORT                432-5224

     EMERGENCY FROM ANY LOCATION - 408-446-8048
Received: from F29.Tymnet by X930.Tymnet; Tue, 11 Aug 87 14:34:03 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 11 Aug 87 14:25:02 PDT
Return-path: <TYMOPS.N/NILES@EMSTXS.Ontyme.Tymnet> 
From: TYMOPS.N/NILES@EMSTXS.Ontyme.Tymnet 
Date: 11 AUG 87 21:50:27 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M11586@Ontyme.Tymnet 
Subject: FURNITURE TAGGING 

     TO:       SOUTH BAY CONSOLIDATION EMPLOYEES

     FROM:     GINA ZWAAGSTRA

     DATE:     AUGUST 11, 1987

     SUBJECT:  FURNITURE TAGGING
     =================================================================

     STARTING AUGUST 11, 1986 THERE WILL BE 4 TEAMS OF 2 PEOPLE COMING
     AROUND TO TAG EXISTING FURNITURE.  BEFORE EACH OF THE NEXT MOVES.

     PLEASE DO NOT REMOVE THE TAGS FROM THE FURNITURE AS THIS WILL
     CAUSE GREAT CONFUSION AND A SHORTAGE FOR THE MOVES.

     THANK YOU FOR YOUR PATIENCE AND COOPERATION!!!
    O¨