CTEST SETPROC
CTEST ADDPROC LISTER=(MPL)TYPER
CTEST ADDPROC TECO=(JMS)TECO
CTEST ADDPROC MACRO=(FTSYS)REXMAC
CTEST ADDPROC LOADER=(FTSYS)LINKER
CTEST SETDOLIST DEFAULT,LOG,(XEXEC),(SPL),(MPL),(M33),(FTSYS),(SYS)
CTEST ADDDOLIST (CARL),(OSMAN),(WRS)
CTEST SETMAIL MAIL.BOX
CTEST MAKINI
R TC
RPG
:ESCAPE
DIRECT RPG.INI
